AWSTemplateFormatVersion: 2010-09-09
Description: delwiki template with nested stacks
Parameters:
  NestedTemplateBucket:
    Type: String
  RDSClusterName:
    Type: String
    Default: "slack-cluster"
  SecretName:
    Type: String
  DatabaseNameP:
    Type: String
    Default: "slackdb"
  DatabaseReadReplicaName:
    Type: String
    Default: "slack-rr"
  DatabaseUsername:
    Type: String
    Default: "slackuser"
  DatabasePasswordKey:
    Type: String
  IAMAuthentication:
    Type: String
    Default: "False"
  ApplicationName:
    Type: String
    Default: slackapp
  EnvironmentClass:
    Type: String
    Default: PRD
    AllowedValues:
    - PRD
  DBInstanceType:
    Type: String
    Default: "db.t3.medium"
  DBSubNetIds:
    Type: String
    Default: "subnet-0d6408c6d1eb47d3b,subnet-0eba1750b8fe27b7e"
  VpcId: 
    Type: String
    Default: "vpc-085e5a8d02267afc1"

Resources: 
  RelationalDataStore:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        DatabaseInstanceType: !Ref DBInstanceType
        RDSClusterName: !Ref RDSClusterName
        DatabaseNameP: !Ref DatabaseNameP
        DatabasePasswordKey: !Ref DatabasePasswordKey
        SecretName: !Ref SecretName
        DatabaseUsername: !Ref DatabaseUsername
        IAMAuthentication: !Ref IAMAuthentication
        VpcId: !Ref VpcId
        DatabaseSubnets:  !Ref DBSubNetIds

      Tags:
        - Key: EnvironmentClass
          Value: !Ref EnvironmentClass    
        - Key: ApplicationName
          Value: !Ref ApplicationName  
      TemplateURL: !Sub https://s3.amazonaws.com/${NestedTemplateBucket}/IAC/rds-mysql.yml 
